//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: base.proto
namespace LSGameServ.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameMessage")]
  public partial class GameMessage : global::ProtoBuf.IExtensible
  {
    public GameMessage() {}
    
    private byte[] _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] type
    {
      get { return _type; }
      set { _type = value; }
    }
    private byte[] _data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqLogin")]
  public partial class ReqLogin : global::ProtoBuf.IExtensible
  {
    public ReqLogin() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfo")]
  public partial class PlayerInfo : global::ProtoBuf.IExtensible
  {
    public PlayerInfo() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _win;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"win", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int win
    {
      get { return _win; }
      set { _win = value; }
    }
    private int _defeat;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"defeat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int defeat
    {
      get { return _defeat; }
      set { _defeat = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomInfo")]
  public partial class RoomInfo : global::ProtoBuf.IExtensible
  {
    public RoomInfo() {}
    
    private int _playercount;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playercount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playercount
    {
      get { return _playercount; }
      set { _playercount = value; }
    }
    private int _roomstatus;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomstatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomstatus
    {
      get { return _roomstatus; }
      set { _roomstatus = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomPlayer")]
  public partial class RoomPlayer : global::ProtoBuf.IExtensible
  {
    public RoomPlayer() {}
    
    private int _team;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"team", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int team
    {
      get { return _team; }
      set { _team = value; }
    }
    private int _isOwner;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isOwner", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int isOwner
    {
      get { return _isOwner; }
      set { _isOwner = value; }
    }
    private LSGameServ.Protobuf.PlayerInfo _playerinfo;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"playerinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public LSGameServ.Protobuf.PlayerInfo playerinfo
    {
      get { return _playerinfo; }
      set { _playerinfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattlePlayer")]
  public partial class BattlePlayer : global::ProtoBuf.IExtensible
  {
    public BattlePlayer() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _team;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"team", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int team
    {
      get { return _team; }
      set { _team = value; }
    }
    private int _swopId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"swopId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int swopId
    {
      get { return _swopId; }
      set { _swopId = value; }
    }
    private int _playerHp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"playerHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerHp
    {
      get { return _playerHp; }
      set { _playerHp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnitInfo")]
  public partial class UnitInfo : global::ProtoBuf.IExtensible
  {
    public UnitInfo() {}
    
    private float _posX;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"posX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posX
    {
      get { return _posX; }
      set { _posX = value; }
    }
    private float _posY;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"posY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posY
    {
      get { return _posY; }
      set { _posY = value; }
    }
    private float _posZ;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"posZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posZ
    {
      get { return _posZ; }
      set { _posZ = value; }
    }
    private float _rotateX;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"rotateX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotateX
    {
      get { return _rotateX; }
      set { _rotateX = value; }
    }
    private float _rotateY;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"rotateY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotateY
    {
      get { return _rotateY; }
      set { _rotateY = value; }
    }
    private float _rotateZ;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"rotateZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotateZ
    {
      get { return _rotateZ; }
      set { _rotateZ = value; }
    }
    private uint _moveState;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"moveState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint moveState
    {
      get { return _moveState; }
      set { _moveState = value; }
    }
    private float _input_h;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"input_h", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float input_h
    {
      get { return _input_h; }
      set { _input_h = value; }
    }
    private float _input_v;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"input_v", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float input_v
    {
      get { return _input_v; }
      set { _input_v = value; }
    }
    private string _id;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShootInfo")]
  public partial class ShootInfo : global::ProtoBuf.IExtensible
  {
    public ShootInfo() {}
    
    private float _posX;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"posX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posX
    {
      get { return _posX; }
      set { _posX = value; }
    }
    private float _posY;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"posY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posY
    {
      get { return _posY; }
      set { _posY = value; }
    }
    private float _posZ;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"posZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posZ
    {
      get { return _posZ; }
      set { _posZ = value; }
    }
    private float _rotateX;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"rotateX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotateX
    {
      get { return _rotateX; }
      set { _rotateX = value; }
    }
    private float _rotateY;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"rotateY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotateY
    {
      get { return _rotateY; }
      set { _rotateY = value; }
    }
    private float _rotateZ;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"rotateZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotateZ
    {
      get { return _rotateZ; }
      set { _rotateZ = value; }
    }
    private string _id;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HitInfo")]
  public partial class HitInfo : global::ProtoBuf.IExtensible
  {
    public HitInfo() {}
    
    private string _attId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"attId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string attId
    {
      get { return _attId; }
      set { _attId = value; }
    }
    private int _damage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damage
    {
      get { return _damage; }
      set { _damage = value; }
    }

    private string _defId = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"defId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string defId
    {
      get { return _defId; }
      set { _defId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleScore")]
  public partial class BattleScore : global::ProtoBuf.IExtensible
  {
    public BattleScore() {}
    
    private int _scoreT1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"scoreT1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int scoreT1
    {
      get { return _scoreT1; }
      set { _scoreT1 = value; }
    }
    private int _scoreT2;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"scoreT2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int scoreT2
    {
      get { return _scoreT2; }
      set { _scoreT2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleCommand")]
  public partial class BattleCommand : global::ProtoBuf.IExtensible
  {
    public BattleCommand() {}
    
    private byte[] _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _userid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private byte[] _data;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGameStart")]
  public partial class ReqGameStart : global::ProtoBuf.IExtensible
  {
    public ReqGameStart() {}
    
    private uint _userid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private uint _roomid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomid
    {
      get { return _roomid; }
      set { _roomid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqStartMove")]
  public partial class ReqStartMove : global::ProtoBuf.IExtensible
  {
    public ReqStartMove() {}
    
    private uint _userid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private uint _roomid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomid
    {
      get { return _roomid; }
      set { _roomid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChangeDir")]
  public partial class ReqChangeDir : global::ProtoBuf.IExtensible
  {
    public ReqChangeDir() {}
    
    private uint _userid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private uint _roomid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomid
    {
      get { return _roomid; }
      set { _roomid = value; }
    }
    private int _angle;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqEndMove")]
  public partial class ReqEndMove : global::ProtoBuf.IExtensible
  {
    public ReqEndMove() {}
    
    private uint _userid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private uint _roomid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomid
    {
      get { return _roomid; }
      set { _roomid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}